rootProject.name = 'BeignetStarter'
apply from: file("../node_modules/@react-native/gradle-plugin/settings.gradle")
apply from: file("../node_modules/react-native/scripts/autolinking.gradle")

includeBuild('../node_modules/@react-native/gradle-plugin')

include ':app'
project(':app').projectDir = new File(rootProject.projectDir, 'app')
